DATASET_PATH = 'test_cases.xlsx'

TYPE = "Type"
KEY = "Key"
CASE_NAME = "Case_Name"
STEPS = "Steps"
STEP_ID = "Step_ID"
LIST_COLUMN = ["Type", "Key", "Case_Name", "Step_ID", "Steps"]

VECTOR_DIMENSION = 200
WORKER_COUNT = 4
WORD_FREQUENCY_THRESHOLD = 2
CONTEXT_WINDOW_SIZE = 2
DOWN_SAMPLING = 1e-3

K_MEANS_CLUSTER_COUNT = 25
